version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_BASE_URL=http://localhost:8080/api/v1
        - NEXT_PUBLIC_ORIGIN=http://localhost:8080
    volumes:
      - node_modules_cache:/app/node_modules
    ports:
      - "3000:3000"

volumes:
  node_modules_cache:
